version: '3.7'

services:

  vectorisation-app:
    image: vectorisation-app:dev
    ports:
      - '8000:80'
    build:
      context: ./apps/vectorisationApp/

  postgres:
    image: postgres:13.3-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./dev/postgres/init:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'PostgresPassword123!'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
      - "xpack.security.enabled=false"  # Disable authentication
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data


  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "xpack.security.enabled=false"  # Disable authentication
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
  postgres-data:
